# Generated by Django 5.0.6 on 2024-06-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_jobopening_jobdetails_and_more'),
        ('users', '0002_applicantprofile_delete_jobseekerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.applicantprofile'),
            preserve_default=False,
        ),
    ]
