# Generated by Django 5.0.6 on 2024-06-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_details',
            new_name='job_id',
        ),
    ]
